feat: add seed to db
CodersCamp2021-HK/CodersCamp2021.Project.Fullstack pull request #116
Opened 2022-03-23 11:54 UTC by KamilDudek

chciałem to jakoś podpiąć pod dockera, ale coś nie idzie. Więc na razie to przez compass np mozna sobie wczytac

2022-04-13 16:38 UTC, hkawalek requested changes
Dobra, możemy na razie przyjąć takie najprostsze rozwiązanie. Jedyne co to przenieś opis command z `README.md` do `docs/seed.md`. Mógłbyś też dodać więcej przykładów dla restauracji i dań.

2022-04-21 17:44 UTC, jskrajna reviewed
Hmm, ogólnie wszystko jest super, tylko ja bym dała jakieś lepiej wyglądające zdjęcia dań i nazwy, bo to jest pozornie nieważne, ale wpływa na na odbiór projektu (i na demo i później jeśli będziemy się chcieli tym pochwalić :) ).

Ja Ci mogę jak coś podesłać jakieś spoko zdjęcia z unsplasha.

Ale generalnie dobra robota :)

2022-04-27 20:54 UTC, tchojnacki commented
W sumie jakbyś przeniósł ten plik jak Hubert mówił wyżej to można by to już zamknąć 👍 

> Dobra, możemy na razie przyjąć takie najprostsze rozwiązanie. Jedyne co to przenieś opis command z README.md do docs/seed.md. Mógłbyś też dodać więcej przykładów dla restauracji i dań.

2022-05-06 13:03 UTC, KamilDudek commented
> W sumie jakbyś przeniósł ten plik jak Hubert mówił wyżej to można by to już zamknąć 👍
> 
> > Dobra, możemy na razie przyjąć takie najprostsze rozwiązanie. Jedyne co to przenieś opis command z README.md do docs/seed.md.

Zmienione, można dać już łapki w górę 🗡️

2022-05-06 16:14 UTC, jskrajna approved these changes
Wyczekane, ale jak pięknie ! Brawo :)

2022-05-07 06:30 UTC, htk4 approved these changes

2022-05-07 10:40 UTC, merged