Users tests don't send mails
CodersCamp2021-HK/CodersCamp2021.Project.Fullstack pull request #139
Opened 2022-04-03 09:27 UTC by KamilDudek

2022-04-05 14:59 UTC, tchojnacki commented on packages/server/src/auth/domain/RegisterAsUserHandler.ts
> +    if (process.env.NODE_ENV != 'test') {
```suggestion
    if (process.env.NODE_ENV !== 'test') {
```

2022-04-05 14:59 UTC, tchojnacki commented on packages/server/src/orders/domain/CreateOrderHandler.ts
> +      if (mail != null && process.env.NODE_ENV != 'test') {
```suggestion
      if (mail != null && process.env.NODE_ENV !== 'test') {
```

Nie wiem czy porównanie `mail != null` ma sens, bo `mail` ma typ `string | undefined`. Biorąc pod uwagę, że mamy abstract equality comparison, to zadziała bo tam `null` i `undefined` są traktowane tak samo, ale porównanie z `null`em zmiennej która nigdy nie może być `null`em jest trochę mylące. (wiem że to nie była zmiana w tym PR, ale jak już jesteśmy w tym nawiasie może warto powiedzieć)

2022-04-05 15:12 UTC, KamilDudek commented on packages/server/src/orders/domain/CreateOrderHandler.ts
> +      if (mail != null && process.env.NODE_ENV != 'test') {
to nie moje, tak było więc nie wiem :/ ale no mogę zmienic :D

2022-04-05 17:56 UTC, htk4 requested changes

2022-04-05 17:56 UTC, htk4 commented on packages/server/src/auth/domain/RegisterAsUserHandler.ts
> +    if (process.env.NODE_ENV !== 'test') {
Ten if ma dwa problemy:

1. jest nieskalowalny - dodając w innym miejscu wysyłanie maila trzeba znowu dodać if-a i tak w kółko,
2. kod aplikacji nie powinien wiedzieć o tym, że jest testowany, bo jakby nie było to aplikacja działa bez testów.

Te problemy można [w bardzo łatwy sposób rozwiązać korzystając z Dependency Injection](https://docs.nestjs.com/fundamentals/testing#end-to-end-testing). Wystarczy w testach podmienić service odpowiedzialny za wysyłanie maila na jakiś jego stub, np.
```ts
class MailerServiceStub {
  sendMail(sendMailOptions: ISendMailOptions) {
    return Promise.resolve({ status: 200, options: sendMailOptions });
  }
}
```
podmiana DI dla testów [tutaj](https://github.com/CodersCamp2021-HK/CodersCamp2021.Project.Fullstack/blob/main/packages/server/test/shared/E2eFixture.ts#L30-L33):
```ts
    const moduleFixture: TestingModule = await override(
      Test.createTestingModule({
        imports: [AppModule],
        controllers: options.testControllers,
      })
        .overrideProvider(MailerService)
        .useClass(MailerServiceStub),
    ).compile();
```

P.S. w JS można to też rozwiązać w inny sposób, ze względu na dynamiczny system importu modułów, można w testach użyć `jest.mock('../module')`, ale to rozwiązanie nie skaluje się do innych języków programowania więc lepiej korzystać z DI.

2022-04-07 20:36 UTC, tchojnacki approved these changes
Nie mam jak w tej chwili wejść na skrzynkę żeby sprawdzić czy faktycznie się nie wysyłają, ale ze strony kodu wszystko wydaje się ok.

2022-04-08 15:02 UTC, htk4 approved these changes
👍🏻

2022-04-10 10:51 UTC, merged