Implement basic home page #133
CodersCamp2021-HK/CodersCamp2021.Project.Fullstack pull request #140
Opened 2022-04-05 16:32 UTC by tchojnacki

2022-04-09 20:32 UTC, mmejer approved these changes
Wygląda dobrze 🚀

2022-04-09 20:32 UTC, mmejer commented on packages/client/src/components/AppNavBar.tsx
> +    <AppBar sx={{ background: '#1B5E2014' }} position='fixed'>
Zastanawia mnie czy nie lepiej dodać kolor `#edf2ed` do naszego `theme` zamiast korzystać z `primary: main` z przezroczystością, skoro i tak wtedy trzeba hardcodować ten kolor. Co o tym myślisz? Zmieniłybyśmy wtedy to w Figmie

2022-04-09 20:38 UTC, jskrajna requested changes
Super zobaczyć, że już coś jest !

Mam drobne uwagi:
- Trochę mi ten główny tytuł inaczej wygląda (chyba powinien być większy i grubszy)
- Moglibyśmy zmniejszyć trochę zdjęcie główne bo ma ponad 1MB.

A tak to jest ekstra ! 

Na marginesie Ci napiszę, że tam weszła drobna modyfikacja tej strony startowej, dojdzie tam input i sekcje takie marketingowe, ale to już jest oddzielny temat od Twojego taska, bo to trzeba dopiero zaaprobować.

2022-04-09 21:00 UTC, tchojnacki commented
Piszę z telefonu także momentami będę leciał z pamięci bo nie mam jak sprawdzić.

---

@mmejer 
> EDIT: Jeszcze co do nagłówka - to tylko kwestia poprawności, ale przeniosłabym "z" do nowej linii 😅. Chociaż z drugiej strony razem z responsywnością to się tak czy tak popsuje chyba

Mogę jutro spróbować wrzucić `&nbsp;` to wtedy na żadnej rozdzielczości nie powinno rozdzielać jak dobrze pójdzie. 👍 

> Zastanawia mnie czy nie lepiej dodać kolor #edf2ed do naszego theme zamiast korzystać z primary: main z przezroczystością, skoro i tak wtedy trzeba hardcodować ten kolor. Co o tym myślisz? Zmieniłybyśmy wtedy to w Figmie

Właśnie główny problem polegał na tym co wspomniałem w opisie PR, że TS bardzo się nie podoba dodawanie własnych zmiennych do theme bo chciałem to `#edf2ed` dodać do `background->appBar` albo `appBar->background` albo coś. W teorii interfejsy są rozszerzalne więc definiując jeszcze raz ten interfejs z takimi właściwościami powinno działać, ale nie chciało 😞 Powalczę jeszcze jutro.

---

@jskrajna 
> Trochę mi ten główny tytuł inaczej wygląda (chyba powinien być większy i grubszy)

Na jakiej rozdzielczości patrzyłaś? Bo na dużych (około 1500 wzwyż, nie pamiętam dokładnej liczby), czyli na takiej jak Figma (bo tam jest 1920) powinno być dobrze - 96px. Na mniejszych musiałem troszeczkę zmniejszyć bo się fizycznie nie mieściło na ekranie.

> Moglibyśmy zmniejszyć trochę zdjęcie główne bo ma ponad 1MB.

Tak zrobię 👍

2022-04-10 11:31 UTC, jskrajna commented
> Piszę z telefonu także momentami będę leciał z pamięci bo nie mam jak sprawdzić.
> 
> @mmejer
> 
> > EDIT: Jeszcze co do nagłówka - to tylko kwestia poprawności, ale przeniosłabym "z" do nowej linii 😅. Chociaż z drugiej strony razem z responsywnością to się tak czy tak popsuje chyba
> 
> Mogę jutro spróbować wrzucić `&nbsp;` to wtedy na żadnej rozdzielczości nie powinno rozdzielać jak dobrze pójdzie. 👍
> 
> > Zastanawia mnie czy nie lepiej dodać kolor #edf2ed do naszego theme zamiast korzystać z primary: main z przezroczystością, skoro i tak wtedy trzeba hardcodować ten kolor. Co o tym myślisz? Zmieniłybyśmy wtedy to w Figmie
> 
> Właśnie główny problem polegał na tym co wspomniałem w opisie PR, że TS bardzo się nie podoba dodawanie własnych zmiennych do theme bo chciałem to `#edf2ed` dodać do `background->appBar` albo `appBar->background` albo coś. W teorii interfejsy są rozszerzalne więc definiując jeszcze raz ten interfejs z takimi właściwościami powinno działać, ale nie chciało 😞 Powalczę jeszcze jutro.
> 
> @jskrajna
> 
> > Trochę mi ten główny tytuł inaczej wygląda (chyba powinien być większy i grubszy)
> 
> Na jakiej rozdzielczości patrzyłaś? Bo na dużych (około 1500 wzwyż, nie pamiętam dokładnej liczby), czyli na takiej jak Figma (bo tam jest 1920) powinno być dobrze - 96px. Na mniejszych musiałem troszeczkę zmniejszyć bo się fizycznie nie mieściło na ekranie.
> 
> > Moglibyśmy zmniejszyć trochę zdjęcie główne bo ma ponad 1MB.
> 
> Tak zrobię 👍

Masz rację ! Patrzyłam na mniejszej rozdzielczości.

2022-04-10 11:32 UTC, jskrajna approved these changes
Jest git :)

2022-04-10 11:49 UTC, tchojnacki commented
@mmejer @jskrajna Ogarnąłem chyba wszystko o czym mówiliśmy, dam wam jeszcze chwilkę na przejrzenie i jak nie będzie zastrzeżeń to przed callem merguję 🚀

2022-04-10 14:04 UTC, merged