Finish implementation of home page #150
CodersCamp2021-HK/CodersCamp2021.Project.Fullstack pull request #154
Opened 2022-04-16 17:37 UTC by tchojnacki

Resolves #150

2022-04-18 12:29 UTC, jskrajna requested changes
Wygląda super ! Dwie drobne uwagi:
- chyba robiąc responsywność musiała uciec jakaś wysokość dla kontenera, bo content z pierwszej sekcji jest mocno przesunięty do góry.
- na spotkaniu była rozmowa, że strzałka zielona jest trochę myląca, więc ja ją ostatecznie usunęłam z projektu, ale jak ona już jest i jest scroll zrobiony to może zrobimy drugą wersję. Jakbyś mógł tylko dodać nad strzałką tekst: "zobacz jak dokonać zamówienia". Wtedy myśle że będzie git :)

2022-04-18 13:22 UTC, tchojnacki commented
> chyba robiąc responsywność musiała uciec jakaś wysokość dla kontenera, bo content z pierwszej sekcji jest mocno przesunięty do góry.

Huh, faktycznie, wychodzi na to, że trafiłem na [nierozwiązany do dziś bug z 2009](https://bugs.webkit.org/show_bug.cgi?id=26559). Poprawione 👍 

---

> Jakbyś mógł tylko dodać nad strzałką tekst: "zobacz jak dokonać zamówienie". Wtedy myśle że będzie git :)

Coś takiego?

![obraz](https://user-images.githubusercontent.com/22599621/163813983-38410a18-f4ec-4de0-9695-490b2576684c.png)

2022-04-18 15:21 UTC, jskrajna commented
> > chyba robiąc responsywność musiała uciec jakaś wysokość dla kontenera, bo content z pierwszej sekcji jest mocno przesunięty do góry.
> 
> Huh, faktycznie, wychodzi na to, że trafiłem na [nierozwiązany do dziś bug z 2009](https://bugs.webkit.org/show_bug.cgi?id=26559). Poprawione 👍
> 
> > Jakbyś mógł tylko dodać nad strzałką tekst: "zobacz jak dokonać zamówienie". Wtedy myśle że będzie git :)
> 
> Coś takiego?
> 
> ![obraz](https://user-images.githubusercontent.com/22599621/163813983-38410a18-f4ec-4de0-9695-490b2576684c.png)

Tak, jest super !

2022-04-18 15:22 UTC, jskrajna approved these changes
Super !

2022-04-20 14:09 UTC, KamilDudek approved these changes

2022-04-20 15:16 UTC, merged