Issue 189 implement payment page third shopping card subpage
CodersCamp2021-HK/CodersCamp2021.Project.Fullstack pull request #205
Opened 2022-05-08 11:11 UTC by KamilDudek

2022-05-08 14:27 UTC, jskrajna requested changes
Wygląda super, fajnie, że są testy i storybook. Dodałabym tylko klikalne te _stepy_ (oprocz tego na którym jesteśmy) żeby można było wrócić do poprzednich .

2022-05-08 16:00 UTC, tchojnacki commented
> Wygląda super, fajnie, że są testy i storybook. Dodałabym tylko klikalne te _stepy_ (oprocz tego na którym jesteśmy) żeby można było wrócić do poprzednich .

Jak coś to jest jeszcze task #201 i tam można to ruszyć.

2022-05-08 16:06 UTC, jskrajna approved these changes

2022-05-11 10:16 UTC, mmejer approved these changes
Bardzo fajnie, dobra robota 🥳

2022-05-11 10:38 UTC, merged