Add order editing functionality to the OrderSummary & CartSummary components #192
CodersCamp2021-HK/CodersCamp2021.Project.Fullstack pull request #206
Opened 2022-05-08 11:53 UTC by tchojnacki

Resolves #192

2022-05-13 15:28 UTC, jskrajna requested changes
Nie jestem pewna co nie gra, bo aż tak się nie wgryzałam, ale w podsumowaniu zamówienia (w kolejnym kroku po wyborze dań na dany dzień) po dokonaniu edycji zmienia się kolejność dań. Do tego stopnia, że danie z jednego dnia wskakuje na inny dzień :D

Jakbyś nie mógł znaleźć tego buga to postaram się to dokładniej opisać, daj znać :)

2022-05-13 19:20 UTC, tchojnacki commented
> Nie jestem pewna co nie gra, bo aż tak się nie wgryzałam, ale w podsumowaniu zamówienia (w kolejnym kroku po wyborze dań na dany dzień) po dokonaniu edycji zmienia się kolejność dań. Do tego stopnia, że danie z jednego dnia wskakuje na inny dzień :D

Chyba wiem o co chodzi, zrobiłem w jednym miejscu skrót i chyba nie był tak sprytny jak mi się wydawało 😆 Zobaczę co i jak.

2022-05-15 19:29 UTC, tchojnacki commented
@jskrajna poprawione, był spory konflikt, ale testy jednostowe i manualne działają więc liczę że przy mergu się nic nie zepsuło.

2022-05-15 19:46 UTC, jskrajna approved these changes
Super !

2022-05-17 18:17 UTC, mmejer approved these changes
Wygląda na to, że wszystko działa. Super 🤩

2022-05-17 18:37 UTC, merged