add tooltip and badge
CodersCamp2021-HK/CodersCamp2021.Project.Fullstack pull request #217
Opened 2022-05-16 21:17 UTC by jskrajna

Mniej więcej dodałam, ale chce jeszcze sobie sprawdzić jak będą zmiany z #192

2022-05-22 16:35 UTC, tchojnacki requested changes

2022-05-22 16:35 UTC, tchojnacki commented on .vscode/settings.json
>  {
Zmiany tego pliku są tu celowo? :thinking: 

Ogólnie chyba gdzieś niechcący przekonfigurowałaś spacje na taby, bo jest pełno zmian które edytują tylko whitespace. Spróbuj coś z tym ogarnać, krzyczy Prettier + trudno się czyta zmiany w PRze (bo cały plik oznacza się jako modyfikowany).

2022-05-22 16:35 UTC, tchojnacki commented on packages/client/src/components/AppNavBar/AppNavBar.tsx
> +					<Button variant='contained' color='secondary' sx={{ borderRadius: '50%', ml: 2, p: 2 }}>
Wydaje mi się, że tego buttona nie powinno tu być:
- nie ma żadnego `onClick`a -> skoro nic nie robi przy interakcji to nie musi być przyciskiem (i psuje accessibility)
- zbędnie pozwala klikać koszyk też kiedy nie ma żadnych dań

Jeśli chodziło tylko o kolor tła to IMO `Box` jak wcześniej wystarczy.

2022-05-22 16:35 UTC, tchojnacki commented on packages/client/src/contexts/ShoppingCartContext.tsx
> +  // const [dishesSum, setDishesSum] = useState<Number | null>(null);
Nieaktualne?

2022-05-22 16:35 UTC, tchojnacki commented on packages/client/src/components/AppNavBar/AppNavBar.tsx
> +	}, [cart, sumAllCartDishes]);
```suggestion

  const dishesSum = sumAllCartDishes(cart);
```

Możesz takie wartości wyliczać zwyczajnie, używasz o 2 hooki mniej i potencjalnie unikasz dodatkowych rerenderów. Możesz dorzucić `useMemo` jeśli martwisz się o wydajność.

- https://prateeksurana.me/blog/why-you-should-avoid-using-state-for-computed-properties/
- https://www.robinwieruch.de/react-computed-properties/

---

Możesz też zwracać od razu `dishesSum` z kontekstu (jak chyba kiedyś próbowałaś), nawet będzie lepiej, bo obecnie zwracana jest funkcja, która jest pure i nigdy się nie zmienia (więc nie ma potrzeby przekazywać jej kontekstem).

Wtedy analogicznie, przerzucasz linijkę którą tu wrzuciłem do kontekstu i zmieniasz w `value` `sumAllCartDishes` na `dishesSum`.

2022-05-22 16:35 UTC, tchojnacki commented on packages/client/src/contexts/ShoppingCartContext.tsx
> +      .flatMap((dish) => dish.count)
```suggestion
      .map((dish) => dish.count)
```

2022-05-23 21:17 UTC, tchojnacki approved these changes
👌

2022-05-23 21:17 UTC, tchojnacki commented on packages/client/src/contexts/ShoppingCartContext.tsx
> +  dishesSum: {} as number,
```suggestion
  dishesSum: 0,
```
(albo inna liczba)

2022-05-24 13:04 UTC, KamilDudek approved these changes

2022-05-24 16:53 UTC, merged