Issue 59 email service
CodersCamp2021-HK/CodersCamp2021.Project.Fullstack pull request #99
Opened 2022-03-16 19:05 UTC by jskrajna

Dodany testowy base dla wysyłania maili, ale mail powienien się już wysyłać przy tworzeniu usera. Muszę to jeszcze ogarnąć bardziej i potestować.

2022-03-16 20:14 UTC, htk4 commented on package.json
> +    "nodemailer": "^6.7.2"
Możesz przenieść `dependencies` do odpowiedniego [packages/server/package.json](https://github.com/CodersCamp2021-HK/CodersCamp2021.Project.Fullstack/blob/main/packages/server/package.json)

Swoją drogą nie potrzebujemy komplikować configa, zamiast używać `@nestjs.config` użyj [Env.ts](https://github.com/CodersCamp2021-HK/CodersCamp2021.Project.Fullstack/blob/main/packages/server/src/config/Env.ts), ustawiając tam potrzebne pola które będą wczytane z pliku .env. Następnie możesz importować env jako zmienną globalną, np. tak jak [tutaj](https://github.com/CodersCamp2021-HK/CodersCamp2021.Project.Fullstack/blob/main/packages/server/src/auth/AuthModule.ts#L26).

2022-03-19 11:39 UTC, tchojnacki commented
Dodałem nowe zmienne środowiskowe do Heroku, także powinno działać na produkcji 👍

2022-03-19 18:28 UTC, htk4 requested changes, later dismissed
Dodałem parę komentarzy, reszta dobrze zrobiona :thumbsup:

2022-03-19 18:28 UTC, hkawalek commented on packages/server/src/mail/AuthMailService.ts
> +  async sendUserConfirmation(user: Auth, token: string) {
Tutaj nie potrzeba całego `user: Auth`, wystarczy `email: string`.

2022-03-19 18:28 UTC, hkawalek commented on packages/server/src/mail/OrderMailService.ts
> +  async sendOrderConfirmation(user: Auth, order: Order) {
Tak samo jak wyżej, wystarczy tylko `email: string` i `orderId: string`.

2022-03-19 18:28 UTC, htk4 commented on packages/server/src/auth/domain/RegisterAsUserHandler.ts
> +    await this.authMailService.sendUserConfirmation(authDoc, 'dcmDkmygBGIILTWaDeP0GFIljjf19R2C');
Przerzuciłbym wysyłanie maila po zapisie do bazy tzn. po `await authDoc.save();`, bo zapis do bazy może się nie udać.

2022-03-19 18:28 UTC, htk4 commented on packages/server/src/orders/domain/CreateOrderHandler.ts
> +    @InjectModel(Auth.name) private readonly authModel: Model<AuthDocument>,
Zamiast importować cały `authModel`, lepiej użyć czegoś w rodzaju `AuthFacade` [Facade pattern](https://refactoring.guru/design-patterns/facade), tak samo zrobiłem [tutaj](https://github.com/CodersCamp2021-HK/CodersCamp2021.Project.Fullstack/blob/main/packages/server/src/restaurants/infra/RestaurantsFacade.ts). Takie rozwiązanie zapewnia lepszą [enkapsulację](https://en.wikipedia.org/wiki/Encapsulation_(computer_programming)) modułów.`AuthFacde` mógłby implemetować taki interfejs:
```ts
interface AuthFacade {
    getEmailByUserId(id: string): string;
}
```

2022-03-19 18:28 UTC, htk4 commented on packages/server/src/orders/domain/CreateOrderHandler.ts
> +    const userDoc = await this.authModel.findOne({ entityId: req.userId });
Kolejność działać powinna być tutaj odwrócona, tzn:

1. Sprawdzić czy istnieje user, jeżeli nie, zwrócić [422](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422)
2. Sprawdzić czy istnieją takie dania jakie zamówił user i czy należą do danej restauracji, jeżeli nie, zwrócić [422](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422)
3. Stworzyć order
4. Wysłać email

2022-03-19 19:16 UTC, jskrajna commented on packages/server/src/auth/domain/RegisterAsUserHandler.ts
> +    await this.authMailService.sendUserConfirmation(authDoc, 'dcmDkmygBGIILTWaDeP0GFIljjf19R2C');
słuszna uwaga !

2022-03-20 09:41 UTC, jskrajna commented on packages/server/src/orders/domain/CreateOrderHandler.ts
> +    @InjectModel(Auth.name) private readonly authModel: Model<AuthDocument>,
dodałam, mam nadzieję że o coś takiego chodziło :)

2022-03-20 18:34 UTC, tchojnacki approved these changes
Wychodząc z założenia, że reszta w kolejnym issue, wygląda ok.

2022-03-20 18:55 UTC, htk4 approved these changes
Wygląda ok 👍🏻

2022-03-20 19:06 UTC, merged